name: Build lisperati

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: lisperati
      - uses: 40ants/run-tests@v2-beta
        with:
          asdf-system: lisperati
