# gcc -Wall -Wextra -pedantic -O0 -ggdb util.c /home/sendai/projects/challenges/cryptopals/set1/2.c -o out && ./out
CFLAGS := -Wall -Wextra -pedantic -O0 -ggdb
1:; $(CC) $(CFLAGS) utils.c $@.c -o out
2:; $(CC) $(CFLAGS) utils.c $@.c -o out
3:; $(CC) $(CFLAGS) utils.c $@.c -o out
4:; $(CC) $(CFLAGS) utils.c $@.c -o out
5:; $(CC) $(CFLAGS) utils.c $@.c -o out
6:; $(CC) $(CFLAGS) utils.c $@.c -o out
