# gcc -Wall -Wextra -pedantic -O0 -ggdb util.c /home/sendai/projects/challenges/cryptopals/set1/2.c -o out && ./out
CFLAGS := -Wall -Wextra -pedantic -O0 -ggdb
4:; $(CC) $(CFLAGS) utils.c $@.c -o out
