* Advent of Code 2025

This year I intend to solve what I can with [[https://factorcode.org/][Factor]]. I will post here some notes I have about the problems and the language.

** Day 1

Really enjoying [[https://docs.factorcode.org/content/vocab-peg.ebnf.html][peg.ebnf]]. Having as proper parser on what is sometimes called *Advent of Parse* is freeing in a way.

** Day 2

Hit an unexpected issue with Part 2 when trying to rely on *regular expressions*. Seems like the [[https://docs.factorcode.org/content/vocab-regexp.html][regex]] vocabulary [[https://docs.factorcode.org/content/article-regexp-syntax.html][doesn't have group capture support]]. Luckly there is [[https://docs.factorcode.org/content/vocab-pcre.html][pcre]] support.

** Day 3
** Day 4

I took the naive approach of iterating across each cell and around it. But since this was really procedural (at least in my head) I just used [[https://www.gnu.org/software/gawk/][AWK]]. It has 2D arrays and is all I needed.

** Day 5

Part 1 ended up being really idiomatic (i think). Parsing doing most of the work. Is nice having a [[https://docs.factorcode.org/content/article-ranges.html][range]] tuple class.
Part 2 took me a while. Something I didn't expected was that the *union* of two *range* types ends up in a expanded sequence even when they overlap. So I did the shuffling manually. (bi,2bi,bi*,bi@,2bi,or,not,2bi)

** Day 6

*** Part 1

I could visualize the parsing in AWK. Unfortunately, there is no *eval()* equivalent in it. And I didn't want to spawn a process for it.
I though EBNF would not work for Factor since this needed process columns, but I was wrong as I just needed to *transpose*. No major issues other than when I tried to be extra clever and parse the operations to quotation. Factor didn't like evaluating run-time quotations.
